---
version: '3.7'
services: 
  squashtmle:
    image: squash-tm-le
    ports:
      - 8081:8080/tcp
    links:
      - postgre-squash
    environment:
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - DATABASE=${DB_DATABASE}

  postgre-squash:
    image: postgres:9.6
    volumes:
      - DB_backup:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
volumes:
  DB_backup: